### ISSUE TITLE
SOAP PartnerConnection query method does not support dot (.) operator relationship queries

### ISSUE THREAD

**Issue by beccagaspard** [palominolabs/sf-api-connector#2]
Here's my SOQL query:

``` sql
select a.RecordType.Name from Account a
```

The result is an SObject with a field named RecordType that is always set to null.

The problem area of the code appears to be in the com.teamlazerbeez.crm.sf.soap.SObjects convertStubSObjectToFacadeSObject method.  This method doesn't account for a queryResult with nested SObjects.

``` java
if ("QueryResult".equals(xsiTypeValue)) {
    PartnerQueryResult subqueryResult = parseQueryResult(xmlElt);
    newSObject.setRelationshipQueryResult(fieldName, subqueryResult);
}
else if ("sf:sObject".equals(xsiTypeValue)){
    //TODO we need to do something different here...
}
else {
    String fieldValue = extractFieldValue(xmlElt);
    newSObject.setField(fieldName, fieldValue);
}
```

Here's a snippet of the raw SOAP response for this query:

``` xml
...
<queryResponse>
    <result xsi:type="QueryResult">
        <done>true</done>
        <queryLocator xsi:nil="true"/>
        <records xsi:type="sf:sObject">
            <sf:type>Account</sf:type>
            <sf:Id>000000000000000000</sf:Id>
            <sf:RecordType xsi:type="sf:sObject">
                <sf:type>RecordType</sf:type>
                <sf:Id xsi:nil="true"/>
                <sf:Name>My Account</sf:Name>
            </sf:RecordType>
        </records>
    </result>
</queryResponse>
...
```

**Comment by marshallpierce** [comment]
Thanks for the detailed bug report! I'll look into it.

**Comment by beccagaspard** [comment]
I forked your repo and wrote a quick workaround - not sure if it is the "best" approach though... https://github.com/beccagaspard/sf-api-connector/commit/d439bec3ccace9a6fc054c2454725cc713671386

**Comment by marshallpierce** [comment]
I think your workaround is along the right lines, but judging by https://www.salesforce.com/us/developer/docs/dbcom_soql_sosl/index_Left.htm#StartTopic=Content/sforce_api_calls_soql_relationships.htm the dot-style of relationship query can never have a query locator, require queryMore(), etc. So, I think it should actually be exposed in a different way on a SObject instead of through the existing relationship query results map.

What do you think about something like this:

```
public PartnerSObject getRelationshipSubObject(String referenceName)
```

which would be used something like this:

```
SObject ownerUser = account.getRelationshipSubObject("Owner");
assert ownerUser.getType().equals("User");
```

Would that make sense given your use case for dot relationship queries?

**Comment by marshallpierce** [comment]
I just pushed something similar to what I described above. Let me know if it solves your problem. It's probably about time to cut a 1.0.0. :)

**Comment by beccagaspard** [comment]
Just tested it out - seems to be working great! :) Thanks!
